# Preamble

In [55]:
import sys

sys.path.append("../src/helpers")
import mlflow
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from mlflow.tracking import MlflowClient
from scipy.stats import pearsonr
from mlflow_utils import mlflow_tracking_uri

client = MlflowClient(tracking_uri=mlflow_tracking_uri)
experiment_id_mapping = experiment_id_mapping = {
    "cifar10-resnet": "206",
    "cifar100-resnet": "210",
    "mufac-resnet": "208",
    "cifar10-vit": "211",
    "cifar100-vit": "212",
    "mufac-vit": "213",
    "50-cifar10-resnet": "218",
    "50-cifar100-resnet": "219",
    "50-cifar10-vit": "220",
    "50-cifar100-vit": "221",
    "tiny-imagenet-resnet": "336",
    "tiny-imagenet-vit": "727",
}


def get_results(experiment_name, additional_methods=None):
    experiment_id = experiment_id_mapping[experiment_name]
    if "cifar10-resnet" or "cifar-10-vit" in experiment_name:
        alpha = "8.0"
    else:
        alpha = "2.0"
    methods = [
        "original",
        "retrained",
        "finetune",
        "neggrad",
        "relabel",
        "badT",
        "scrub",
        "ssd",
        "unsir",
        "salun_relabel",
        "our",
    ]
    if additional_methods is not None:
        methods += additional_methods

    metrics = [
        "mia",
        "acc_forget",
        "acc_retain",
        "acc_test",
        "acc_val",
        "t",
        "js",
        "js_proxy",
    ]
    runs = client.search_runs(experiment_id)
    df = pd.DataFrame(
        [
            {k: v for k, v in run.data.metrics.items() if k in metrics}
            for run in runs
            if run.data.params.get("method") in methods
            or (
                run.data.params.get("method") == "our"
                and run.data.params.get("alpha") == str(alpha)
            )
        ]
    )
    df["method"] = [
        run.data.params.get("method")
        for run in runs
        if run.data.params.get("method") in methods
        or (
            run.data.params.get("method") == "our"
            and run.data.params.get("alpha") == str(alpha)
        )
    ]

    df["seed"] = [
        run.data.params.get("seed")
        for run in runs
        if run.data.params.get("method") in methods
        or (
            run.data.params.get("method") == "our"
            and run.data.params.get("alpha") == str(alpha)
        )
    ]

    df.set_index(["method", "seed"], inplace=True)

    grouped_df = df.groupby("method").aggregate(["mean", "std"])
    grouped_df["js"] = grouped_df["js"].apply(lambda x: x * 1e4)
    grouped_df["js_proxy"] = grouped_df["js_proxy"].apply(lambda x: x * 1e4)
    grouped_df = grouped_df.round(2)

    # ATTENTION: Original Model has NaN JSD, we fill it with 0, but IT IS NOT TRUE VALUE
    grouped_df = grouped_df.fillna(0)


    gap_metrics = ["mia", "acc_forget", "acc_retain", "acc_test", "acc_val"]
    for method in methods:
        for metric in gap_metrics:
            grouped_df.loc[method, f"{metric}_gap"] = abs(
                grouped_df.loc[method, (metric, "mean")]
                - grouped_df.loc["retrained", (metric, "mean")]
            )
    grouped_df["avg_gap"] = (
        grouped_df[
            [
                "mia_gap",
                "acc_retain_gap",
                "acc_forget_gap",
                "acc_test_gap",
            ]
        ]
        .mean(axis=1)
        .round(4)
    )

    main_df = grouped_df.loc[[method for method in methods],["avg_gap", "js", "t", "js_proxy"]]

    appendix_df = grouped_df.loc[[method for method in methods],["mia", "acc_forget", "acc_retain", "acc_test", "acc_val"]]

    print(experiment_name)
    corr, p_value = pearsonr(main_df[("avg_gap", "")], main_df[("js_proxy", "mean")])
    print(
        f"Pearson correlation between avg_gap and js_proxy: {corr:.2f}, p-value: {p_value:.4f}"
    )

    corr, p_value = pearsonr(main_df[("avg_gap", "")], main_df[("js", "mean")])
    print(
        f"Pearson correlation between avg_gap and js: {corr:.2f}, p-value: {p_value:.4f}"
    )

    corr, p_value = pearsonr(main_df[("js", "mean")], main_df[("js_proxy", "mean")])
    print(
        f"Pearson correlation between js and js_proxy: {corr:.2f}, p-value: {p_value:.4f}"
    )

    # Rename columns in main_df
    main_df.columns = [
        "Avg Gap" if col == ("avg_gap", "") else
        f"JSD({col[1]})" if col[0] == "js" else
        f"Time({col[1]})" if col[0] == "t" else
        f"RF-JSD({col[1]})" if col[0] == "js_proxy" else
        col
        for col in main_df.columns
    ]

    main_df.rename(
    index={
        "retrained": "Gold Std",
        "finetune": "Finetuning",
        "neggrad": "NegGrad+",
        "relabel": "Rnd Labeling",
        "badT": "Bad Teacher",
        "scrub": "SCRUB",
        "ssd": "SSD",
        "unsir": "UNSIR",
        "our": "LoTUS",
        "salun_relabel": "SalUn(RL)",
        "salun_lotus": "SalUn(LoTUS)",
        "our_cifake": "LoTUS(CIFAKE)",
    },
    inplace=True,
    )

    appendix_df.rename(
    index={
        "original": "Original",
        "retrained": "Gold Std",
        "finetune": "Finetuning",
        "neggrad": "NegGrad+",
        "relabel": "Rnd Labeling",
        "badT": "Bad Teacher",
        "scrub": "SCRUB",
        "ssd": "SSD",
        "unsir": "UNSIR",
        "salun_relabel": "SalUn(RL)",
        "our": "LoTUS",
        "our_cifake": "LoTUS(CIFAKE)",
        "our_noGumbel": "LoTUS(NoGumbel)",
    },
    inplace=True,
    )

    display(main_df.head(50))
    display(appendix_df.head(50))

    return main_df, appendix_df

# Instances ResNet18

In [56]:
rn_cifar10, appendix_cifar10 = get_results("cifar10-resnet", additional_methods=["our_cifake", "our_noGumbel"])

cifar10-resnet
Pearson correlation between avg_gap and js_proxy: 0.78, p-value: 0.0016
Pearson correlation between avg_gap and js: 0.91, p-value: 0.0000
Pearson correlation between js and js_proxy: 0.84, p-value: 0.0004

,Avg Gap,JSD(mean),JSD(std),Time(mean),Time(std),RF-JSD(mean),RF-JSD(std)
method,,,,,,,
original,0.0750,0.00,0.00,6.50,0.13,61.12,2.94
Gold Std,0.0000,0.00,0.00,5.32,1.18,5.97,4.69
Finetuning,0.1375,1.03,0.24,0.43,0.00,81.45,6.53
NegGrad+,0.0975,1.06,0.21,0.49,0.00,80.64,21.01
Rnd Labeling,0.0925,1.00,0.26,0.57,0.00,47.98,3.43
Bad Teacher,0.2650,2.39,2.03,0.33,0.00,287.45,157.93
SCRUB,0.0750,0.41,0.09,0.58,0.00,62.39,5.54
SSD,0.0825,0.82,0.57,0.54,0.00,145.86,152.88
UNSIR,0.1075,0.65,0.05,0.45,0.00,17.29,4.21
SalUn(RL),0.1800,1.09,0.05,1.56,0.01,53.43,37.24
LoTUS,0.0350,0.32,0.04,0.29,0.00,19.84,6.53
LoTUS(CIFAKE),0.0300,0.32,0.03,0.30,0.01,12.46,1.31
our_noGumbel,0.0675,0.41,0.09,0.30,0.00,37.89,3.46

                  mia       acc_forget       acc_retain       acc_test        \
                 mean   std       mean   std       mean   std     mean   std
method
Original         0.94  0.00       1.00  0.00       1.00  0.00     0.93  0.01
Gold Std         0.76  0.03       0.91  0.02       0.99  0.02     0.91  0.02
Finetuning       0.30  0.26       0.97  0.01       0.98  0.01     0.89  0.02
NegGrad+         0.48  0.50       0.97  0.01       0.97  0.01     0.88  0.02
Rnd Labeling     0.48  0.50       0.96  0.01       0.97  0.01     0.89  0.02
Bad Teacher      0.43  0.37       0.71  0.18       0.71  0.18     0.66  0.16
SCRUB            0.94  0.01       1.00  0.00       1.00  0.00     0.93  0.01
SSD              0.81  0.11       0.86  0.16       0.87  0.16     0.80  0.15
UNSIR            0.46  0.03       0.93  0.01       0.93  0.01     0.86  0.01
SalUn(RL)        0.16  0.28       0.94  0.02       0.95  0.02     0.86  0.03
LoTUS            0.82  0.10       0.99  0.00       0.99  0.00     0.91  0.01
LoTUS(CIFAKE)    0.72  0.02       0.99  0.00       0.99  0.00     0.91  0.01
LoTUS(NoGumbel)  0.94  0.00       1.00  0.00       0.99  0.00     0.91  0.01

                acc_val
                   mean   std
method
Original           0.93  0.00
Gold Std           0.91  0.02
Finetuning         0.89  0.01
NegGrad+           0.89  0.01
Rnd Labeling       0.89  0.01
Bad Teacher        0.66  0.16
SCRUB              0.93  0.00
SSD                0.80  0.15
UNSIR              0.86  0.01
SalUn(RL)          0.86  0.04
LoTUS              0.92  0.01
LoTUS(CIFAKE)      0.86  0.01
LoTUS(NoGumbel)    0.91  0.01

In [58]:
rn_cifar100, appendix_cifar100 = get_results("cifar100-resnet", additional_methods=["our_noGumbel"])

cifar100-resnet
Pearson correlation between avg_gap and js_proxy: 0.84, p-value: 0.0006
Pearson correlation between avg_gap and js: 0.87, p-value: 0.0002
Pearson correlation between js and js_proxy: 0.96, p-value: 0.0000

,Avg Gap,JSD(mean),JSD(std),Time(mean),Time(std),RF-JSD(mean),RF-JSD(std)
method,,,,,,,
original,0.1625,0.00,0.00,1.79,0.26,19.05,2.29
Gold Std,0.0000,0.00,0.00,3.39,0.30,16.34,1.58
Finetuning,0.3600,6.88,0.59,0.43,0.00,101.26,19.61
NegGrad+,0.3575,6.87,0.62,0.49,0.00,101.75,19.85
Rnd Labeling,0.4025,5.84,0.98,0.57,0.00,74.93,20.53
Bad Teacher,0.3675,4.30,0.49,0.34,0.01,63.04,8.91
SCRUB,0.1650,1.87,0.08,0.58,0.00,18.79,1.96
SSD,0.2125,3.04,1.55,0.54,0.00,42.17,36.59
UNSIR,0.3625,3.05,0.32,0.45,0.00,40.02,8.51
SalUn(RL),0.3650,6.50,0.60,1.55,0.01,82.56,16.12
LoTUS,0.1200,1.67,0.37,0.30,0.01,16.36,8.40
our_noGumbel,0.1025,1.34,0.01,0.30,0.00,9.04,0.28

                  mia       acc_forget       acc_retain       acc_test        \
                 mean   std       mean   std       mean   std     mean   std
method
Original         0.77  0.05       0.93  0.04       0.93  0.03     0.60  0.02
Gold Std         0.49  0.01       0.57  0.02       0.94  0.03     0.60  0.02
Finetuning       0.00  0.00       0.40  0.06       0.41  0.06     0.35  0.05
NegGrad+         0.00  0.00       0.41  0.06       0.41  0.06     0.35  0.05
Rnd Labeling     0.00  0.00       0.31  0.06       0.37  0.07     0.31  0.06
Bad Teacher      0.33  0.58       0.27  0.03       0.28  0.03     0.25  0.03
SCRUB            0.78  0.05       0.93  0.03       0.93  0.03     0.60  0.02
SSD              0.59  0.05       0.50  0.32       0.50  0.32     0.36  0.20
UNSIR            0.00  0.00       0.40  0.07       0.41  0.07     0.34  0.04
SalUn(RL)        0.00  0.00       0.38  0.04       0.41  0.04     0.35  0.03
LoTUS            0.28  0.22       0.81  0.08       0.92  0.02     0.61  0.01
LoTUS(NoGumbel)  0.55  0.02       0.88  0.04       0.94  0.04     0.64  0.02

                acc_val
                   mean   std
method
Original           0.60  0.02
Gold Std           0.60  0.01
Finetuning         0.35  0.04
NegGrad+           0.35  0.04
Rnd Labeling       0.31  0.05
Bad Teacher        0.25  0.03
SCRUB              0.60  0.02
SSD                0.35  0.19
UNSIR              0.34  0.04
SalUn(RL)          0.35  0.03
LoTUS              0.61  0.02
LoTUS(NoGumbel)    0.62  0.02

In [59]:
rn_tiny_imagenet, appendix_tiny_imagenet = get_results("tiny-imagenet-resnet", additional_methods=["our_noGumbel"])

KeyError: 'our_noGumbel'

In [60]:
rn_mufac, appendix_mufac = get_results("mufac-resnet", additional_methods=["our_noGumbel"])

KeyError: 'our_noGumbel'

# Instances ViT

In [48]:
vit_cifar10, appendix_df = get_results("cifar10-vit", additional_methods=["our_cifake"])

cifar10-vit
Pearson correlation between avg_gap and js_proxy: 0.86, p-value: 0.0003
Pearson correlation between avg_gap and js: 0.96, p-value: 0.0000
Pearson correlation between js and js_proxy: 0.91, p-value: 0.0000

,Avg Gap,JSD(mean),JSD(std),Time(mean),Time(std),RF-JSD(mean),RF-JSD(std)
method,,,,,,,
original,0.0050,0.00,0.00,84.50,9.51,2.88,0.23
Gold Std,0.0000,0.00,0.00,111.00,1.99,1.66,0.37
Finetuning,0.0075,0.01,0.00,11.33,0.03,3.26,0.68
NegGrad+,0.0125,0.03,0.00,12.61,0.03,6.12,0.25
Rnd Labeling,0.0125,0.02,0.01,12.78,0.01,2.11,0.51
Bad Teacher,0.0375,0.12,0.03,8.79,0.02,9.21,3.18
SCRUB,0.0050,0.01,0.00,16.66,0.02,2.81,0.20
SSD,0.0075,0.02,0.01,13.65,0.02,2.69,0.22
UNSIR,0.0100,0.01,0.01,10.68,0.02,2.41,0.66
SalUn(RL),0.0125,0.01,0.01,37.97,0.19,2.07,0.26
LoTUS,0.0050,0.01,0.00,7.34,0.25,2.08,0.29
LoTUS(CIFAKE),0.0075,0.01,0.00,7.25,0.06,1.96,0.28

                mia       acc_forget       acc_retain       acc_test        \
               mean   std       mean   std       mean   std     mean   std
method
Original       0.88  0.00       1.00  0.00       1.00  0.00     0.99  0.01
Gold Std       0.88  0.01       0.99  0.00       1.00  0.00     0.98  0.01
Finetuning     0.90  0.00       0.99  0.00       1.00  0.00     0.99  0.00
NegGrad+       0.91  0.00       1.00  0.00       1.00  0.00     0.99  0.01
Rnd Labeling   0.84  0.02       0.99  0.00       1.00  0.00     0.99  0.01
Bad Teacher    0.81  0.02       0.96  0.01       0.97  0.01     0.96  0.01
SCRUB          0.88  0.00       1.00  0.00       1.00  0.00     0.99  0.01
SSD            0.89  0.01       1.00  0.01       1.00  0.01     0.99  0.01
UNSIR          0.90  0.00       0.99  0.00       0.99  0.00     0.99  0.01
SalUn(RL)      0.84  0.02       0.99  0.00       1.00  0.00     0.99  0.01
LoTUS          0.87  0.00       1.00  0.00       1.00  0.00     0.98  0.01
LoTUS(CIFAKE)  0.89  0.00       1.00  0.00       1.00  0.00     0.99  0.00

              acc_val
                 mean   std
method
Original         0.98  0.00
Gold Std         0.98  0.00
Finetuning       0.99  0.01
NegGrad+         0.99  0.00
Rnd Labeling     0.99  0.00
Bad Teacher      0.96  0.00
SCRUB            0.98  0.00
SSD              0.98  0.01
UNSIR            0.98  0.00
SalUn(RL)        0.99  0.00
LoTUS            0.98  0.00
LoTUS(CIFAKE)    0.95  0.00

In [14]:
vit_cifar100, appendix_df = get_results("cifar100-vit")

cifar100-vit
Pearson correlation between avg_gap and js_proxy: 0.68, p-value: 0.0202
Pearson correlation between avg_gap and js: 0.85, p-value: 0.0008
Pearson correlation between js and js_proxy: 0.86, p-value: 0.0008

,Avg Gap,JSD(mean),JSD(std),Time(mean),Time(std),RF-JSD(mean),RF-JSD(std)
method,,,,,,,
original,0.0200,0.00,0.00,121.85,2.20,2.04,0.10
Gold Std,0.0000,0.00,0.00,112.25,0.13,2.58,0.08
Finetuning,0.0275,0.07,0.00,11.35,0.00,3.12,0.17
NegGrad+,0.0325,0.13,0.01,12.63,0.01,3.37,0.12
Rnd Labeling,0.0175,0.06,0.00,12.79,0.02,2.74,0.17
Bad Teacher,0.0375,0.17,0.01,9.18,0.27,3.80,0.22
SCRUB,0.0200,0.04,0.00,16.74,0.03,2.04,0.09
SSD,0.0175,0.04,0.00,13.67,0.02,2.08,0.13
UNSIR,0.0250,0.08,0.01,10.69,0.01,3.11,0.19
SalUn(RL),0.0200,0.06,0.01,38.15,0.04,2.69,0.17
LoTUS,0.0125,0.04,0.02,7.02,0.01,2.00,0.34

               mia       acc_forget       acc_retain       acc_test        \
              mean   std       mean   std       mean   std     mean   std
method
Original      0.75  0.00       0.97  0.01       0.96  0.00     0.91  0.01
Gold Std      0.72  0.00       0.92  0.00       0.96  0.00     0.91  0.00
Finetuning    0.77  0.00       0.95  0.01       0.98  0.00     0.92  0.01
NegGrad+      0.79  0.02       0.97  0.02       0.97  0.02     0.91  0.01
Rnd Labeling  0.74  0.01       0.94  0.00       0.98  0.00     0.92  0.00
Bad Teacher   0.66  0.01       0.90  0.01       0.91  0.00     0.89  0.01
SCRUB         0.75  0.00       0.97  0.00       0.96  0.00     0.91  0.01
SSD           0.75  0.01       0.96  0.01       0.96  0.00     0.91  0.00
UNSIR         0.78  0.01       0.94  0.00       0.95  0.01     0.90  0.01
SalUn(RL)     0.75  0.01       0.94  0.01       0.98  0.01     0.92  0.00
LoTUS         0.71  0.02       0.96  0.01       0.96  0.00     0.91  0.00

             acc_val
                mean   std
method
Original        0.92  0.01
Gold Std        0.91  0.01
Finetuning      0.92  0.00
NegGrad+        0.91  0.01
Rnd Labeling    0.92  0.00
Bad Teacher     0.88  0.01
SCRUB           0.92  0.01
SSD             0.91  0.01
UNSIR           0.91  0.00
SalUn(RL)       0.92  0.01
LoTUS           0.92  0.01

In [15]:
vit_mufac, appendix_df = get_results("mufac-vit")

mufac-vit
Pearson correlation between avg_gap and js_proxy: 0.97, p-value: 0.0000
Pearson correlation between avg_gap and js: 0.96, p-value: 0.0000
Pearson correlation between js and js_proxy: 0.93, p-value: 0.0000

,Avg Gap,JSD(mean),JSD(std),Time(mean),Time(std),RF-JSD(mean),RF-JSD(std)
method,,,,,,,
original,0.0200,0.00,0.00,16.47,0.02,9.31,0.84
Gold Std,0.0000,0.00,0.00,13.83,0.01,12.89,0.10
Finetuning,0.0400,0.27,0.02,1.40,0.01,18.46,6.75
NegGrad+,0.0475,0.39,0.04,1.67,0.00,20.68,6.78
Rnd Labeling,0.0200,0.35,0.09,1.76,0.01,22.58,3.92
Bad Teacher,0.1750,1.89,1.01,2.09,0.25,201.41,191.09
SCRUB,0.0200,0.05,0.02,2.21,0.01,8.27,0.60
SSD,0.0200,0.17,0.17,1.91,0.00,14.89,9.32
UNSIR,0.0475,0.85,0.06,3.21,0.01,23.52,8.34
SalUn(RL),0.0200,0.29,0.01,8.15,0.01,19.21,7.70
LoTUS,0.0200,0.05,0.01,1.09,0.00,10.24,0.44

               mia       acc_forget       acc_retain       acc_test        \
              mean   std       mean   std       mean   std     mean   std
method
Original      0.58  0.01       0.63  0.01       0.66  0.01     0.66  0.01
Gold Std      0.57  0.00       0.57  0.01       0.66  0.01     0.65  0.01
Finetuning    0.52  0.08       0.61  0.01       0.72  0.01     0.66  0.01
NegGrad+      0.52  0.07       0.66  0.02       0.71  0.01     0.65  0.03
Rnd Labeling  0.52  0.10       0.58  0.01       0.67  0.02     0.64  0.01
Bad Teacher   0.35  0.05       0.43  0.06       0.47  0.07     0.50  0.08
SCRUB         0.59  0.01       0.62  0.01       0.66  0.01     0.66  0.01
SSD           0.59  0.01       0.59  0.04       0.63  0.04     0.64  0.01
UNSIR         0.47  0.08       0.58  0.01       0.72  0.01     0.63  0.02
SalUn(RL)     0.53  0.12       0.58  0.01       0.68  0.01     0.64  0.02
LoTUS         0.59  0.01       0.63  0.01       0.66  0.00     0.65  0.01

             acc_val
                mean   std
method
Original        0.62  0.00
Gold Std        0.62  0.01
Finetuning      0.64  0.02
NegGrad+        0.64  0.01
Rnd Labeling    0.60  0.02
Bad Teacher     0.48  0.07
SCRUB           0.62  0.00
SSD             0.62  0.01
UNSIR           0.60  0.01
SalUn(RL)       0.60  0.02
LoTUS           0.62  0.01

# 50% forget set

In [16]:
rn50_cifar10, appendix_df = get_results("50-cifar10-resnet")

50-cifar10-resnet
Pearson correlation between avg_gap and js_proxy: 0.70, p-value: 0.0165
Pearson correlation between avg_gap and js: 0.54, p-value: 0.0878
Pearson correlation between js and js_proxy: 0.31, p-value: 0.3482

,Avg Gap,JSD(mean),JSD(std),Time(mean),Time(std),RF-JSD(mean),RF-JSD(std)
method,,,,,,,
original,0.1100,0.00,0.00,7.01,0.13,57.34,4.14
Gold Std,0.0000,0.00,0.00,2.52,0.26,14.50,0.31
Finetuning,0.1100,0.31,0.00,0.26,0.01,34.78,7.45
NegGrad+,0.1475,0.31,0.01,0.51,0.02,32.29,4.88
Rnd Labeling,0.2100,0.73,0.22,0.48,0.00,525.89,202.57
Bad Teacher,0.0625,0.18,0.02,0.57,0.02,13.22,3.10
SCRUB,0.1075,0.14,0.00,0.61,0.02,56.79,4.83
SSD,0.1025,0.13,0.00,1.27,0.02,42.11,6.47
UNSIR,0.1025,0.21,0.05,0.73,0.00,14.82,4.96
SalUn(RL),0.1300,1.40,0.02,1.49,0.01,22.88,3.80
LoTUS,0.0650,0.09,0.01,0.57,0.00,11.15,1.41

               mia       acc_forget       acc_retain       acc_test        \
              mean   std       mean   std       mean   std     mean   std
method
Original      0.94  0.00       1.00  0.00       1.00  0.00     0.93  0.01
Gold Std      0.73  0.01       0.86  0.01       0.98  0.01     0.86  0.01
Finetuning    0.44  0.01       0.97  0.01       0.97  0.01     0.89  0.01
NegGrad+      0.29  0.25       0.97  0.01       0.97  0.01     0.89  0.01
Rnd Labeling  0.87  0.23       0.69  0.09       0.69  0.09     0.62  0.07
Bad Teacher   0.59  0.17       0.92  0.02       0.93  0.02     0.86  0.02
SCRUB         0.93  0.01       1.00  0.00       1.00  0.00     0.93  0.01
SSD           0.92  0.01       1.00  0.00       1.00  0.00     0.92  0.01
UNSIR         0.45  0.05       0.94  0.02       0.94  0.02     0.87  0.02
SalUn(RL)     0.33  0.58       0.95  0.01       0.98  0.01     0.89  0.01
LoTUS         0.79  0.02       0.99  0.01       0.99  0.00     0.92  0.01

             acc_val
                mean   std
method
Original        0.93  0.00
Gold Std        0.86  0.01
Finetuning      0.89  0.01
NegGrad+        0.89  0.01
Rnd Labeling    0.63  0.07
Bad Teacher     0.87  0.01
SCRUB           0.93  0.00
SSD             0.93  0.01
UNSIR           0.87  0.01
SalUn(RL)       0.89  0.01
LoTUS           0.92  0.01

In [17]:
rn50_cifar100, appendix_df = get_results("50-cifar100-resnet")

50-cifar100-resnet
Pearson correlation between avg_gap and js_proxy: 0.79, p-value: 0.0041
Pearson correlation between avg_gap and js: 0.43, p-value: 0.1869
Pearson correlation between js and js_proxy: 0.62, p-value: 0.0422

,Avg Gap,JSD(mean),JSD(std),Time(mean),Time(std),RF-JSD(mean),RF-JSD(std)
method,,,,,,,
original,0.2225,0.00,0.00,1.93,0.27,15.08,2.18
Gold Std,0.0000,0.00,0.00,1.94,0.06,11.85,0.36
Finetuning,0.3200,1.39,0.10,0.26,0.01,70.78,16.60
NegGrad+,0.3150,1.38,0.08,0.52,0.00,70.30,15.65
Rnd Labeling,0.3875,1.03,0.23,0.48,0.00,72.42,28.15
Bad Teacher,0.3050,0.55,0.04,0.58,0.01,49.23,5.14
SCRUB,0.2225,0.44,0.02,0.62,0.00,15.02,2.15
SSD,0.2225,0.44,0.02,1.29,0.03,15.06,2.17
UNSIR,0.2925,0.65,0.23,0.72,0.01,33.83,3.26
SalUn(RL),0.3300,6.25,0.45,1.49,0.01,74.34,16.54
LoTUS,0.1725,0.28,0.00,0.57,0.01,7.66,0.26

               mia       acc_forget       acc_retain       acc_test        \
              mean   std       mean   std       mean   std     mean   std
method
Original      0.78  0.04       0.93  0.03       0.93  0.03     0.60  0.02
Gold Std      0.41  0.01       0.52  0.01       0.98  0.01     0.54  0.01
Finetuning    0.00  0.00       0.41  0.06       0.41  0.07     0.35  0.05
NegGrad+      0.00  0.00       0.42  0.06       0.42  0.06     0.35  0.05
Rnd Labeling  0.00  0.00       0.30  0.10       0.33  0.11     0.27  0.09
Bad Teacher   0.67  0.58       0.36  0.05       0.38  0.05     0.34  0.04
SCRUB         0.78  0.04       0.93  0.03       0.93  0.03     0.60  0.02
SSD           0.78  0.04       0.93  0.03       0.93  0.03     0.60  0.02
UNSIR         0.00  0.00       0.45  0.06       0.46  0.06     0.37  0.04
SalUn(RL)     0.00  0.00       0.36  0.03       0.42  0.05     0.35  0.04
LoTUS         0.57  0.02       0.91  0.03       0.92  0.03     0.62  0.02

             acc_val
                mean   std
method
Original        0.60  0.02
Gold Std        0.54  0.02
Finetuning      0.35  0.05
NegGrad+        0.35  0.04
Rnd Labeling    0.27  0.08
Bad Teacher     0.34  0.04
SCRUB           0.60  0.02
SSD             0.60  0.02
UNSIR           0.37  0.04
SalUn(RL)       0.35  0.03
LoTUS           0.61  0.02

In [18]:
vit50_cifar10, appendix_df = get_results("50-cifar10-vit")

50-cifar10-vit
Pearson correlation between avg_gap and js_proxy: 0.96, p-value: 0.0000
Pearson correlation between avg_gap and js: 0.80, p-value: 0.0028
Pearson correlation between js and js_proxy: 0.89, p-value: 0.0002

,Avg Gap,JSD(mean),JSD(std),Time(mean),Time(std),RF-JSD(mean),RF-JSD(std)
method,,,,,,,
original,0.0125,0.00,0.00,86.35,8.62,2.38,0.20
Gold Std,0.0000,0.00,0.00,64.09,2.60,1.19,0.24
Finetuning,0.0125,0.00,0.00,6.48,0.27,1.83,0.12
NegGrad+,0.0200,0.01,0.00,12.97,0.50,5.67,0.56
Rnd Labeling,0.0050,0.00,0.00,12.60,0.03,1.46,0.10
Bad Teacher,0.0600,0.04,0.01,15.10,0.20,28.75,4.47
SCRUB,0.0125,0.00,0.00,16.99,0.35,2.40,0.21
SSD,0.0150,0.00,0.00,19.03,0.54,2.38,0.25
UNSIR,0.0150,0.00,0.00,18.33,0.02,1.31,0.16
SalUn(RL),0.0050,0.02,0.00,37.93,0.18,2.21,0.63
LoTUS,0.0050,0.00,0.00,14.09,0.53,1.18,0.17

               mia       acc_forget       acc_retain       acc_test        \
              mean   std       mean   std       mean   std     mean   std
method
Original      0.87  0.01       1.00  0.00       1.00  0.00     0.99  0.01
Gold Std      0.84  0.01       0.99  0.01       1.00  0.00     0.98  0.00
Finetuning    0.88  0.01       0.99  0.00       1.00  0.00     0.99  0.01
NegGrad+      0.90  0.00       1.00  0.00       1.00  0.00     0.99  0.00
Rnd Labeling  0.82  0.02       0.99  0.00       1.00  0.00     0.98  0.01
Bad Teacher   0.76  0.01       0.93  0.01       0.95  0.01     0.93  0.01
SCRUB         0.87  0.01       1.00  0.00       1.00  0.00     0.99  0.01
SSD           0.88  0.01       1.00  0.00       1.00  0.00     0.99  0.01
UNSIR         0.89  0.00       0.99  0.00       0.99  0.00     0.98  0.00
SalUn(RL)     0.85  0.01       0.99  0.00       1.00  0.00     0.99  0.01
LoTUS         0.83  0.01       1.00  0.00       1.00  0.00     0.98  0.01

             acc_val
                mean   std
method
Original        0.98  0.00
Gold Std        0.98  0.00
Finetuning      0.99  0.00
NegGrad+        0.99  0.00
Rnd Labeling    0.98  0.00
Bad Teacher     0.93  0.01
SCRUB           0.98  0.00
SSD             0.98  0.01
UNSIR           0.98  0.01
SalUn(RL)       0.99  0.00
LoTUS           0.98  0.00

In [19]:
vit50_cifar100, appendix_df = get_results("50-cifar100-vit")

50-cifar100-vit
Pearson correlation between avg_gap and js_proxy: 0.63, p-value: 0.0381
Pearson correlation between avg_gap and js: 0.46, p-value: 0.1506
Pearson correlation between js and js_proxy: 0.66, p-value: 0.0259

,Avg Gap,JSD(mean),JSD(std),Time(mean),Time(std),RF-JSD(mean),RF-JSD(std)
method,,,,,,,
original,0.0350,0.00,0.00,122.52,2.28,1.53,0.06
Gold Std,0.0000,0.00,0.00,62.71,0.11,1.93,0.09
Finetuning,0.0400,0.02,0.00,6.34,0.01,1.90,0.08
NegGrad+,0.0600,0.03,0.01,12.68,0.02,2.96,0.19
Rnd Labeling,0.0250,0.01,0.01,12.62,0.02,1.60,0.08
Bad Teacher,0.0575,0.06,0.01,15.04,0.03,4.63,0.32
SCRUB,0.0350,0.01,0.00,16.82,0.03,1.54,0.06
SSD,0.0350,0.01,0.00,18.69,0.06,1.53,0.07
UNSIR,0.0375,0.02,0.00,18.33,0.02,2.07,0.12
SalUn(RL),0.0375,0.10,0.01,38.08,0.02,2.69,0.17
LoTUS,0.0225,0.01,0.00,13.79,0.02,1.44,0.10

               mia       acc_forget       acc_retain       acc_test        \
              mean   std       mean   std       mean   std     mean   std
method
Original      0.75  0.00       0.96  0.00       0.96  0.00     0.91  0.01
Gold Std      0.68  0.00       0.91  0.01       0.95  0.00     0.90  0.00
Finetuning    0.75  0.01       0.94  0.00       0.99  0.01     0.92  0.01
NegGrad+      0.80  0.00       0.98  0.00       0.98  0.00     0.92  0.00
Rnd Labeling  0.72  0.01       0.94  0.00       0.97  0.01     0.91  0.01
Bad Teacher   0.65  0.01       0.85  0.01       0.87  0.01     0.84  0.00
SCRUB         0.75  0.00       0.96  0.00       0.96  0.00     0.91  0.01
SSD           0.75  0.00       0.96  0.00       0.96  0.00     0.91  0.01
UNSIR         0.78  0.01       0.94  0.01       0.96  0.00     0.91  0.00
SalUn(RL)     0.75  0.01       0.94  0.01       0.98  0.01     0.92  0.00
LoTUS         0.70  0.00       0.96  0.00       0.96  0.01     0.91  0.00

             acc_val
                mean   std
method
Original        0.92  0.01
Gold Std        0.90  0.01
Finetuning      0.91  0.01
NegGrad+        0.92  0.00
Rnd Labeling    0.92  0.01
Bad Teacher     0.83  0.01
SCRUB           0.92  0.01
SSD             0.92  0.01
UNSIR           0.91  0.00
SalUn(RL)       0.92  0.01
LoTUS           0.91  0.00

# Plots

In [20]:
# def plot_avg_gap(df, title):
#     df_sorted = df.sort_values(by="Avg Gap", ascending=True)

#     fig, ax = plt.subplots(figsize=(5, 3.5))
#     fig.suptitle(title, fontsize=12, fontname="Times New Roman")

#     # Sort by value
#     df_sorted = df.sort_values(
#         by="Avg Gap",
#         ascending=True,
#         key=lambda x: x.where(df.index != "LoTUS", x - 0.0001),
#     )
#     # Define colors for the bars
#     colors = ["red" if method == "LoTUS" else "gray" for method in df_sorted.index]

#     df_sorted["Avg Gap"].plot(kind="bar", ax=ax, color=colors, edgecolor="black")
#     ax.set_title("Average Gap", fontsize=10, fontname="Times New Roman")
#     ax.set_xlabel("Method", fontsize=10, fontname="Times New Roman")
#     ax.set_ylabel("Avg Gap (mean)", fontsize=10, fontname="Times New Roman")
#     ax.tick_params(axis="x", rotation=45, labelsize=9)
#     ax.tick_params(axis="y", labelsize=9)
#     for label in ax.get_xticklabels() + ax.get_yticklabels():
#         label.set_fontname("Times New Roman")

#     plt.tight_layout(rect=[0, 0, 1, 1])
#     plt.show()


# # Plot avg_gap for each dataframe
# plot_avg_gap(rn_cifar10, "ResNet18 CIFAR-10 - Avg Gap")
# plot_avg_gap(rn_cifar100, "ResNet18 CIFAR-100 - Avg Gap")
# plot_avg_gap(rn_mufac, "ResNet18 MUFAC - Avg Gap")
# plot_avg_gap(vit_cifar10, "ViT CIFAR-10 - Avg Gap")
# plot_avg_gap(vit_cifar100, "ViT CIFAR-100 - Avg Gap")
# plot_avg_gap(vit_mufac, "ViT MUFAC - Avg Gap")

In [21]:
# def plot_js_divergence(df, title):
#     df_sorted_js = df.sort_values(by="JSD(mean)", ascending=True, key=lambda x: x.where(df.index != 'LoTUS', x - 0.0001))

#     fig, ax = plt.subplots(figsize=(4, 3))

#     # Define colors for the bars
#     colors_js = ['red' if method == 'LoTUS' else 'gray' for method in df_sorted_js.index]

#     # Plot js
#     df_sorted_js["JSD(mean)"].plot(kind='bar', yerr=df_sorted_js["JSD(std)"], ax=ax, color=colors_js, edgecolor='black', capsize=4)
#     ax.set_title(title, fontsize=12, fontname='Times New Roman')
#     ax.set_xlabel(None)
#     ax.set_ylabel('JS Div. (mean ± std) x 1e4', fontsize=10, fontname='Times New Roman')
#     ax.tick_params(axis='x', rotation=45, labelsize=9)
#     ax.tick_params(axis='y', labelsize=9)
#     for label in ax.get_xticklabels() + ax.get_yticklabels():
#         label.set_fontname('Times New Roman')

#     plt.tight_layout(rect=[0, 0, 1, 1])
#     plt.savefig(f'images/{title}_js_divergence.png', bbox_inches='tight', dpi=300)
#     plt.show()

# # Plot JS divergence for each dataframe
# plot_js_divergence(rn_cifar10, "ResNet18 CIFAR-10")
# plot_js_divergence(rn_cifar100, "ResNet18 CIFAR-100")
# plot_js_divergence(rn_mufac, "ResNet18 MUFAC")
# plot_js_divergence(vit_cifar10, "ViT CIFAR-10")
# plot_js_divergence(vit_cifar100, "ViT CIFAR-100")
# plot_js_divergence(vit_mufac, "ViT MUFAC")

In [22]:
# def plot_time(df, title):
#     df_sorted = df.sort_values(by="Time(mean)", ascending=True)

#     fig, ax = plt.subplots(figsize=(3, 2.5))
#     fig.suptitle(title, fontsize=12, fontname="Times New Roman")

#     # Sort by value
#     df_sorted = df.sort_values(
#         by="Time(mean)",
#         ascending=True,
#         key=lambda x: x.where(df.index != "LoTUS", x - 1e-32),
#     )
#     # Define colors for the bars
#     colors = ["red" if method == "LoTUS" else "grey" for method in df_sorted.index]

#     df_sorted["Time(mean)"].plot(kind="bar", ax=ax, color=colors, edgecolor="black")
#     ax.set_xlabel(None)
#     ax.set_ylabel("Execution Time (min.)", fontsize=12, fontname="Times New Roman")
#     ax.tick_params(axis="y", labelsize=10)
#     for label in ax.get_yticklabels():
#         label.set_fontname("Times New Roman")
#     plt.savefig(f'images/time/{title}.png', bbox_inches='tight', dpi=300)
#     plt.show()


# # Plot (t, mean) for each dataframe
# plot_time(rn_cifar10, "ResNet18 - CIFAR-10")
# plot_time(rn_cifar100, "ResNet18 - CIFAR-100")
# plot_time(rn_mufac, "ResNet18 -MUFAC")
# plot_time(vit_cifar10, "ViT - CIFAR-10")
# plot_time(vit_cifar100, "ViT - CIFAR-100")
# plot_time(vit_mufac, "ViT - MUFAC")